spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: aman
    password: aman
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 69B39BBA31A4F5A6CD8DB8B6DE919C89A18C31D527EF1B21EACBD4BC9B
      expiration: 8640000